# cloudbuild.yaml
steps:
  # 0. Build Frontend (Next.js)
  - name: "node:20"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd frontend_v3
        npm ci
        npm run build
        # Move dist to where backend expects it (backend/main.py checks frontend/dist)
        # The repo structure has frontend_v3, but main.py checks frontend/dist OR static.
        # Let's ensure it's in the right place.
        # main.py line 284: frontend_build_path = Path("frontend/dist")
        # We need to move frontend_v3/dist to frontend/dist or update main.py.
        # Easiest is to move it to frontend/dist (create dir if needed).
        mkdir -p ../frontend
        # Next.js "output: export" generates an "out" folder.
        # Backend expects "frontend/dist".
        mkdir -p ../frontend
        rm -rf ../frontend/dist
        mv out ../frontend/dist

  # 1. Build Backend Container (includes frontend artifacts)
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/youtube-ai-backend",
        "-f",
        "backend/Dockerfile",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/youtube-ai-backend"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "youtube-ai-backend",
        "--image",
        "gcr.io/$PROJECT_ID/youtube-ai-backend",
        "--platform",
        "managed",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--port",
        "8080",
        "--add-volume=name=persistent-storage,type=cloud-storage,bucket=${PROJECT_ID}-data",
        "--add-volume-mount=volume=persistent-storage,mount-path=/app/persistent",
        "--set-env-vars",
        "DATABASE_URL=sqlite:////app/persistent/youtube_ai.db,DATA_DIR=/app/persistent",
      ]
# For sensitive values, use Google Secret Manager and reference them in Cloud Run env config.

images:
  - "gcr.io/$PROJECT_ID/youtube-ai-backend"

substitutions:
  _OPENAI_API_KEY: ""
  _GOOGLE_TTS_API_KEY: ""
  _DALLE_API_KEY: ""
  _YOUTUBE_CLIENT_ID: ""
  _YOUTUBE_CLIENT_SECRET: ""
  _YOUTUBE_REFRESH_TOKEN: ""
  _GEMINI_API_KEY: ""
  _GROQ_API_KEY: ""
  _SERPER_API_KEY: ""
  _REPLICATE_API_KEY: ""
  _FIGMA_API_KEY: ""
  _MIDJOURNEY_API_KEY: ""
  _PRINTBELLE_API_KEY: ""
  _STRIPE_API_KEY: ""
  _SHOPIFY_API_KEY: ""
  _SHOPIFY_API_SECRET: ""
  _PAYONEER_CUSTOMER_ID: ""
  _DATABASE_URL_PROD: "sqlite:///./youtube_ai.db"
  _REDIS_URL_PROD: ""
  _APP_SECRET_KEY: "change_me_in_production"
  _PAYMENT_SHOPIER_API_KEY: ""
  _PAYMENT_SHOPIER_API_SECRET: ""
  _SHOPIER_PERSONAL_ACCESS_TOKEN: ""
  _SHOPIER_WEBHOOK_TOKEN: ""
  _GCS_DATA_BUCKET: "${PROJECT_ID}-data"

options:
  substitution_option: "ALLOW_LOOSE"
