# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/youtube-ai-backend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/youtube-ai-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'youtube-ai-backend',
      '--image', 'gcr.io/$PROJECT_ID/youtube-ai-backend',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--port', '8080',
      '--set-env-vars',
        'OPENAI_API_KEY=${_OPENAI_API_KEY},GOOGLE_TTS_API_KEY=${_GOOGLE_TTS_API_KEY},DALLE_API_KEY=${_DALLE_API_KEY},YOUTUBE_CLIENT_ID=${_YOUTUBE_CLIENT_ID},YOUTUBE_CLIENT_SECRET=${_YOUTUBE_CLIENT_SECRET},YOUTUBE_REFRESH_TOKEN=${_YOUTUBE_REFRESH_TOKEN},GEMINI_API_KEY=${_GEMINI_API_KEY},GROQ_API_KEY=${_GROQ_API_KEY},SERPER_API_KEY=${_SERPER_API_KEY},REPLICATE_API_KEY=${_REPLICATE_API_KEY},FIGMA_API_KEY=${_FIGMA_API_KEY},MIDJOURNEY_API_KEY=${_MIDJOURNEY_API_KEY},PRINTBELLE_API_KEY=${_PRINTBELLE_API_KEY},STRIPE_API_KEY=${_STRIPE_API_KEY},SHOPIFY_API_KEY=${_SHOPIFY_API_KEY},SHOPIFY_API_SECRET=${_SHOPIFY_API_SECRET},PAYONEER_CUSTOMER_ID=${_PAYONEER_CUSTOMER_ID},DATABASE_URL=${_DATABASE_URL_PROD},REDIS_URL=${_REDIS_URL_PROD},SECRET_KEY=${_APP_SECRET_KEY}'
    ]
# For sensitive values, use Google Secret Manager and reference them in Cloud Run env config.

images:
  - 'gcr.io/$PROJECT_ID/youtube-ai-backend'
