steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_BACKEND_IMAGE}",
        "-f",
        "${_BACKEND_DOCKERFILE}",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_BACKEND_IMAGE}"]

images:
  - "${_BACKEND_IMAGE}"

substitutions:
  _BACKEND_IMAGE: "gcr.io/$PROJECT_ID/autonomax-api"
  _BACKEND_DOCKERFILE: "services/autonomax_api/Dockerfile"

options:
  substitution_option: "ALLOW_LOOSE"
