steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/youtube-ai-backend",
        "-f",
        "backend/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/youtube-ai-backend"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "youtube-ai-backend",
        "--image",
        "gcr.io/$PROJECT_ID/youtube-ai-backend",
        "--platform",
        "managed",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--port",
        "8080",
      ]
images:
  - "gcr.io/$PROJECT_ID/youtube-ai-backend"
